set_property SRC_FILE_INFO {cfile:/home/madhav/AjitHpcBoards_local/AjitHpcBoards/kcu105_cleaned_mark_debug/constraint/kcu105_ethernet.xdc rfile:../../constraint/kcu105_ethernet.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G10 [get_ports {clk_in_p}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F10 [get_ports {clk_in_n}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK17 [get_ports {c0_sys_clk_p}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK16 [get_ports {c0_sys_clk_n}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G25     [get_ports "DEBUG_UART_RX"] ;
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K26     [get_ports "DEBUG_UART_TX"] ;
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM19     [get_ports "SERIAL_UART_RX"] ;
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM17   [get_ports "SERIAL_UART_TX"] ;
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN8      [get_ports {clk_rst}] ;
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH14   [get_ports "c0_ddr4_act_n"]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE17   [get_ports "c0_ddr4_adr[0]"]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH17   [get_ports "c0_ddr4_adr[1]"]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE18   [get_ports "c0_ddr4_adr[2]"]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ15   [get_ports "c0_ddr4_adr[3]"]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG16   [get_ports "c0_ddr4_adr[4]"]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL17   [get_ports "c0_ddr4_adr[5]"]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK18   [get_ports "c0_ddr4_adr[6]"]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG17   [get_ports "c0_ddr4_adr[7]"]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF18   [get_ports "c0_ddr4_adr[8]"]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH19   [get_ports "c0_ddr4_adr[9]"]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF15   [get_ports "c0_ddr4_adr[10]"]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD19   [get_ports "c0_ddr4_adr[11]"]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ14   [get_ports "c0_ddr4_adr[12]"]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG19   [get_ports "c0_ddr4_adr[13]"]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD16   [get_ports "c0_ddr4_adr[14]"]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG14   [get_ports "c0_ddr4_adr[15]"]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF14   [get_ports "c0_ddr4_adr[16]"]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF17   [get_ports "c0_ddr4_ba[0]"]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL15   [get_ports "c0_ddr4_ba[1]"]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG15   [get_ports "c0_ddr4_bg"]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE15   [get_ports "c0_ddr4_ck_c"]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE16   [get_ports "c0_ddr4_ck_t"]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD15   [get_ports "c0_ddr4_cke"]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL19   [get_ports "c0_ddr4_cs_n"]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD21   [get_ports "c0_ddr4_dm_dbi_n[0]"]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE25   [get_ports "c0_ddr4_dm_dbi_n[1]"]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ21   [get_ports "c0_ddr4_dm_dbi_n[2]"]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM21   [get_ports "c0_ddr4_dm_dbi_n[3]"]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH26   [get_ports "c0_ddr4_dm_dbi_n[4]"]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN26   [get_ports "c0_ddr4_dm_dbi_n[5]"]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ29   [get_ports "c0_ddr4_dm_dbi_n[6]"]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL32   [get_ports "c0_ddr4_dm_dbi_n[7]"]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE23   [get_ports "c0_ddr4_dq[0]"]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG20   [get_ports "c0_ddr4_dq[1]"]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF22   [get_ports "c0_ddr4_dq[2]"]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF20   [get_ports "c0_ddr4_dq[3]"]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE22   [get_ports "c0_ddr4_dq[4]"]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD20   [get_ports "c0_ddr4_dq[5]"]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG22   [get_ports "c0_ddr4_dq[6]"]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE20   [get_ports "c0_ddr4_dq[7]"]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ24   [get_ports "c0_ddr4_dq[8]"]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG24   [get_ports "c0_ddr4_dq[9]"]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ23   [get_ports "c0_ddr4_dq[10]"]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF23   [get_ports "c0_ddr4_dq[11]"]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH23   [get_ports "c0_ddr4_dq[12]"]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF24   [get_ports "c0_ddr4_dq[13]"]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH22   [get_ports "c0_ddr4_dq[14]"]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG25   [get_ports "c0_ddr4_dq[15]"]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL22   [get_ports "c0_ddr4_dq[16]"]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL25   [get_ports "c0_ddr4_dq[17]"]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM20   [get_ports "c0_ddr4_dq[18]"]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK23   [get_ports "c0_ddr4_dq[19]"]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK22   [get_ports "c0_ddr4_dq[20]"]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL24   [get_ports "c0_ddr4_dq[21]"]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL20   [get_ports "c0_ddr4_dq[22]"]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL23   [get_ports "c0_ddr4_dq[23]"]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM24   [get_ports "c0_ddr4_dq[24]"]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN23   [get_ports "c0_ddr4_dq[25]"]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN24   [get_ports "c0_ddr4_dq[26]"]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP23   [get_ports "c0_ddr4_dq[27]"]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP25   [get_ports "c0_ddr4_dq[28]"]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN22   [get_ports "c0_ddr4_dq[29]"]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP24   [get_ports "c0_ddr4_dq[30]"]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM22   [get_ports "c0_ddr4_dq[31]"]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH28   [get_ports "c0_ddr4_dq[32]"]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK26   [get_ports "c0_ddr4_dq[33]"]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK28   [get_ports "c0_ddr4_dq[34]"]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM27   [get_ports "c0_ddr4_dq[35]"]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ28   [get_ports "c0_ddr4_dq[36]"]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH27   [get_ports "c0_ddr4_dq[37]"]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK27   [get_ports "c0_ddr4_dq[38]"]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM26   [get_ports "c0_ddr4_dq[39]"]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL30   [get_ports "c0_ddr4_dq[40]"]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP29   [get_ports "c0_ddr4_dq[41]"]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM30   [get_ports "c0_ddr4_dq[42]"]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN28   [get_ports "c0_ddr4_dq[43]"]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL29   [get_ports "c0_ddr4_dq[44]"]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP28   [get_ports "c0_ddr4_dq[45]"]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM29   [get_ports "c0_ddr4_dq[46]"]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN27   [get_ports "c0_ddr4_dq[47]"]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH31   [get_ports "c0_ddr4_dq[48]"]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH32   [get_ports "c0_ddr4_dq[49]"]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ34   [get_ports "c0_ddr4_dq[50]"]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK31   [get_ports "c0_ddr4_dq[51]"]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ31   [get_ports "c0_ddr4_dq[52]"]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ30   [get_ports "c0_ddr4_dq[53]"]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH34   [get_ports "c0_ddr4_dq[54]"]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK32   [get_ports "c0_ddr4_dq[55]"]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN33   [get_ports "c0_ddr4_dq[56]"]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP33   [get_ports "c0_ddr4_dq[57]"]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM34   [get_ports "c0_ddr4_dq[58]"]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP31   [get_ports "c0_ddr4_dq[59]"]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM32   [get_ports "c0_ddr4_dq[60]"]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN31   [get_ports "c0_ddr4_dq[61]"]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL34   [get_ports "c0_ddr4_dq[62]"]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN32   [get_ports "c0_ddr4_dq[63]"]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH21   [get_ports "c0_ddr4_dqs_c[0]"]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ25   [get_ports "c0_ddr4_dqs_c[1]"]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK20   [get_ports "c0_ddr4_dqs_c[2]"]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP21   [get_ports "c0_ddr4_dqs_c[3]"]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL28   [get_ports "c0_ddr4_dqs_c[4]"]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP30   [get_ports "c0_ddr4_dqs_c[5]"]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ33   [get_ports "c0_ddr4_dqs_c[6]"]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP34   [get_ports "c0_ddr4_dqs_c[7]"]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG21   [get_ports "c0_ddr4_dqs_t[0]"]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH24   [get_ports "c0_ddr4_dqs_t[1]"]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ20   [get_ports "c0_ddr4_dqs_t[2]"]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP20   [get_ports "c0_ddr4_dqs_t[3]"]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL27   [get_ports "c0_ddr4_dqs_t[4]"]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN29   [get_ports "c0_ddr4_dqs_t[5]"]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH33   [get_ports "c0_ddr4_dqs_t[6]"]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN34   [get_ports "c0_ddr4_dqs_t[7]"]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ18   [get_ports "c0_ddr4_odt"]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL18   [get_ports "c0_ddr4_reset_n"]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP8     [get_ports {led[0]}]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H23     [get_ports {led[1]}]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P20     [get_ports {led[2]}]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P21     [get_ports {led[3]}]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N22     [get_ports {led[4]}]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M22     [get_ports {led[5]}]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R23     [get_ports {led[6]}]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P23     [get_ports {led[7]}]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N24             [get_ports "phy_sgmii_tx_p"]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M24             [get_ports "phy_sgmii_tx_n"]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P24             [get_ports "phy_sgmii_rx_p"]
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P25             [get_ports "phy_sgmii_rx_n"]
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P26             [get_ports "phy_sgmii_clk_p"]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N26             [get_ports "phy_sgmii_clk_n"]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K25             [get_ports "phy_int_n"]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J23             [get_ports "phy_reset_n"]
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 8.0 -datapath_only -from [get_clocks -include_generated_clocks clk_125mhz_mmcm_out] -to [get_clocks -include_generated_clocks clk125_i]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 8.0 -datapath_only -from [get_clocks -include_generated_clocks clk125_i] -to [get_clocks -include_generated_clocks clk_125mhz_mmcm_out]
set_property src_info {type:XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 10.0 -datapath_only -from [get_clocks -include_generated_clocks clk_out1_clk_wiz_80] -to [get_clocks -include_generated_clocks mmcm_clkout0]
set_property src_info {type:XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 10.0 -datapath_only -from [get_clocks -include_generated_clocks mmcm_clkout0] -to [get_clocks -include_generated_clocks clk_out1_clk_wiz_80]
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 8.0 -datapath_only -from [get_clocks -include_generated_clocks clk_out1_clk_wiz_80] -to [get_clocks -include_generated_clocks clk_125mhz_mmcm_out]
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 8.0 -datapath_only -from [get_clocks -include_generated_clocks clk_125mhz_mmcm_out] -to [get_clocks -include_generated_clocks clk_out1_clk_wiz_80]
set_property src_info {type:XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 8.0 -datapath_only -from [get_clocks -include_generated_clocks clk_out2_clk_wiz_80] -to [get_clocks -include_generated_clocks clk_125mhz_mmcm_out]
set_property src_info {type:XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 8.0 -datapath_only -from [get_clocks -include_generated_clocks clk_125mhz_mmcm_out] -to [get_clocks -include_generated_clocks clk_out2_clk_wiz_80]
set_property src_info {type:XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 8.0 -datapath_only -from [get_clocks -include_generated_clocks clk_125mhz_mmcm_out] -to [get_clocks -include_generated_clocks mmcm_clkout0]
set_property src_info {type:XDC file:1 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 8.0 -datapath_only -from [get_clocks -include_generated_clocks mmcm_clkout0] -to [get_clocks -include_generated_clocks clk_125mhz_mmcm_out]
set_property src_info {type:XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 10.0 -datapath_only -from [get_clocks -include_generated_clocks clk_out1_clk_wiz_80] -to [get_clocks -include_generated_clocks clk_out2_clk_wiz_80]
set_property src_info {type:XDC file:1 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 10.0 -datapath_only -from [get_clocks -include_generated_clocks clk_out2_clk_wiz_80] -to [get_clocks -include_generated_clocks clk_out1_clk_wiz_80]
